### ISSUE TITLE
Error when running pip3

### ISSUE THREAD

**Issue by aabadie** [iot-lab/iot-lab-yocto#1]
I tested the new A8 images on Saclay site and had this error with pip3:
```
root@node-a8-151:~# pip3 --version
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/pkg_resources/__init__.py", line 34, in <module>
  File "/usr/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 4, in <module>
    from enum import IntEnum as _IntEnum
ImportError: No module named 'enum'
```

**Comment by fsaintma** [comment]
Fix commit: 545dc836a0409ce22107ecbaf45a2bbf0918f41f
