### ISSUE TITLE
Error with miniterm.py

### ISSUE THREAD

**Issue by aabadie** [iot-lab/iot-lab-yocto#2]
Tested with basic shell RIOT firmware (`examples/default`). When I type up-arrow, I get this error:
```
root@node-a8-155:~# miniterm.py /dev/ttyA8_M3 500000 -e
^[[B--- Miniterm on /dev/ttyA8_M3  500000,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
Exception in thread tx:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/miniterm.py", line 449, in writer
    self.console.write(echo_text)
  File "/usr/bin/miniterm.py", line 60, in write
    self.output.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u241b' in position 0: ordinal not in range(128)
```

It looks the python installation has problems.

**Comment by fsaintma** [comment]
I cannot reproduce your bug.

I have launched an experiment on Saclay site with one A8 node and compiled default firmware from RIOT (2017.04-branch)

```
> make ETHOS_BAUDRATE=500000 BOARD=iotlab-a8-m3 -C examples/default clean all
```
After I go to A8 node, flash firmware and read serial port with success:

```
root@node-a8-174:~/A8# miniterm.py /dev/ttyA8_M3 500000 -e
--- Miniterm on /dev/ttyA8_M3  500000,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> help

Command              Description
---------------------------------------
reboot               Reboot the node
ps                   Prints information about running threads.
ifconfig             Configure network interfaces
txtsnd               Sends a custom string as is over the link layer
saul                 interact with sensors and actuators using SAUL
>
```

**Comment by aabadie** [comment]
I could also have the shell commands until I hit the up/down arrow on my keyboard.

**Comment by fsaintma** [comment]
Ok I didn't view the up/down arrow :)

**Comment by fsaintma** [comment]
Fix commit: 6123b9c9316a5f43effdbf8e0b7813d174fd9d1e

**Comment by aabadie** [comment]
well done! Is it available in Saclay ?

**Comment by fsaintma** [comment]
Yes it's done on Saclay site :)

**Comment by aabadie** [comment]
thanks ! good job
